#openai_api_key: ""  # Replace with your actual OpenAI key

rss_feeds:
  - "https://techcrunch.com/feed/"
  - "https://www.producthunt.com/feed"
  - "https://www.crunchbase.com/news/feed"

embedding_model: "text-embedding-ada-002"
embedding_provider: "huggingface"  # or "openai"
hf_model: "all-MiniLM-L6-v2"
hf_chat_model: HuggingFaceH4/zephyr-7b-beta
#hf_chat_model: mistralai/Mistral-7B-Instruct-v0.2



#embedding_model: "text-embedding-3-small"
#openai_api_key: "your-key-here"
#chat_model: "gpt-4"  # or "gpt-3.5-turbo"
